version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
      - ./server/e-commerce-models:/app/e-commerce-models
      - ./server/e-commerce-data:/app/e-commerce-data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
